# Configuration comparing alignment methods, preparation approaches
# and variant callers for an NA12878 exome dataset from EdgeBio.
#
# See the bcbio-nextgen documentation for full instructions to
# run this analysis:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
#
# There is also an optional configuration item to compare with Illumina's
# platinum genomes. This requires retrieving the input file from Illumina:
# wget ftp://ftp.platinumgenomes.org/trio/NA12878.vcf.gz
# and uncommenting the relevant section in the configuration.
---
upload:
  dir: ../final
fc_date: '2013-04-03'
fc_name: methodcmp
details:
  - files: [NA12878-NGv3-LAB1360-A_1.fastq.gz, NA12878-NGv3-LAB1360-A_2.fastq.gz]
    lane: 1
    description: NA12878-1
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: novoalign
      variantcaller: [gatk, freebayes, gatk-haplotype]
      quality_format: Standard
      coverage_interval: regional
      merge_bamprep: false
      validate: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-pass.vcf
      validate_regions: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-regions.bed
      variant_regions: /home/bradc/data/NA12878_exome/input/NGv3.bed
  - files: [NA12878-NGv3-LAB1360-A_1.fastq.gz, NA12878-NGv3-LAB1360-A_2.fastq.gz]
    lane: 2
    description: NA12878-2
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      variantcaller: [gatk, freebayes, gatk-haplotype]
      quality_format: Standard
      coverage_interval: regional
      merge_bamprep: false
      validate: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-pass.vcf
      validate_regions: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-regions.bed
      variant_regions: /home/bradc/data/NA12878_exome/input/NGv3.bed
  - files: [NA12878-NGv3-LAB1360-A_1.fastq.gz, NA12878-NGv3-LAB1360-A_2.fastq.gz]
    lane: 3
    description: NA12878-3
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: novoalign
      mark_duplicates: samtools
      recalibrate: false
      realign: gkno
      variantcaller: [gatk, freebayes, gatk-haplotype]
      quality_format: Standard
      coverage_interval: regional
      merge_bamprep: false
      validate: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-pass.vcf
      validate_regions: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-regions.bed
      variant_regions: /home/bradc/data/NA12878_exome/input/NGv3.bed
  - files: [NA12878-NGv3-LAB1360-A_1.fastq.gz, NA12878-NGv3-LAB1360-A_2.fastq.gz]
    lane: 4
    description: NA12878-4
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      mark_duplicates: samtools
      recalibrate: false
      realign: gkno
      variantcaller: [gatk, freebayes, gatk-haplotype]
      quality_format: Standard
      coverage_interval: regional
      merge_bamprep: false
      validate: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-pass.vcf
      validate_regions: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-regions.bed
      variant_regions: /home/bradc/data/NA12878_exome/input/NGv3.bed
  # - vrn_file: /home/bradc/data/NA12878_exome/input/NA12878-illumina-platinum.vcf
  #   lane: 5
  #   description: Illumina-platinum
  #   genome_build: hg19
  #   analysis: variant2
  #   algorithm:
  #     validate: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-pass.vcf
  #     validate_regions: /home/bradc/data/NA12878_exome/input/NA12878-nist-v2_13-NGv3-regions.bed
  #     validate_genome_build: GRCh37
  #     variant_regions: /home/bradc/data/NA12878_exome/input/NGv3.bed
