# Configuration comparing alignment methods, preparation approaches
# and variant callers for an NA12878 exome dataset from EdgeBio.
#
# See the bcbio-nextgen documentation for full instructions to
# run this analysis:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
---
upload:
  dir: ../final
details:
  - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
    description: NA12878-1
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      align_split_size: 5000000
      variantcaller: [gatk, freebayes, gatk-haplotype]
      quality_format: Standard
      coverage_interval: regional
      recalibrate: gatk
      realign: gatk
      merge_bamprep: true
      validate: ../input/GiaB_NIST_RTG_v0_2.vcf.gz
      validate_regions: ../input/GiaB_NIST_RTG_v0_2_regions.bed
      variant_regions: ../input/NGv3.bed
      ensemble:
        format-filters: [DP < 4]
        classifiers: 
          balance: [AD, FS, Entropy]
          calling: [ReadPosEndDist, PL, PLratio, Entropy, NBQ]
        classifier-params:
          type: svm
        trusted-pct: 0.65
  - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
    description: NA12878-2
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      align_split_size: 5000000
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: [gatk, freebayes, gatk-haplotype]
      quality_format: Standard
      coverage_interval: regional
      merge_bamprep: false
      validate: ../input/GiaB_NIST_RTG_v0_2.vcf.gz
      validate_regions: ../input/GiaB_NIST_RTG_v0_2_regions.bed
      variant_regions: ../input/NGv3.bed
      ensemble:
        format-filters: [DP < 4]
        classifiers: 
          balance: [AD, FS, Entropy]
          calling: [ReadPosEndDist, PL, PLratio, Entropy, NBQ]
        classifier-params:
          type: svm
        trusted-pct: 0.65
